backend:
  name: github
  repo: kentam1127g/001
  branch: main
  base_url: https://enpitumark-oath.netlify.app

media_folder: "images/uploads"
public_folder: "images/uploads"

publish_mode: simple

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    delete: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    summary: "{{author}}"

    fields:
      - label: "投稿者"
        name: "author"
        widget: "hidden"
        default: ""

      - label: "画像"
        name: "image"
        widget: "image"
        required: false

      - label: "テキスト"
        name: "text"
        widget: "text"
        required: false

      - label: "画像キャプション"
        name: "caption"
        widget: "string"
        required: false

      - label: "日付"
        name: "date"
        widget: "hidden"
        default: "{{now}}"

      - label: "作成日時"
        name: "createdAt"
        widget: "hidden"
        default: "{{now}}"

      - label: "既読数"
        name: "viewCount"
        widget: "hidden"
        default: 0